Merge `.coco.` and `.ozar.` files (round 8) (#6783)
* merge hero-victory-modal.coco/ozar.sass: flags added

* merge teacher-classes-view.coco/ozar.sass: flags added

* merge site-chrome.coco/ozar.sass: flags added

* merge common.coco/ozar.sass: flags added

* merge ChooseAccountTypeView.coco/ozar.coffee: event listeners and methods applied from both, flags added

* merge ThangTypeConstants.coco/ozar.coffee: flags added, created new objects for the differing properties and assign them on original objects.

* merge user.coco/ozar.coffee: coco version applied. Since we're using the same collection in coco and ozar, the schema should be the same. Flagging differences would make no sense here.

* merge LadderPlayModal.coco/ozar.coffee: flags added, one modification applied from coco to both.

* merge I18NHomeView.coco/ozar.coffee: flags added

* merge SchoolInfoPanel.coco/ozar.coffee: flags added

* Auto merging .coco/.ozar - right side

* Auto merging .coco/.ozar - left side

* merge ThangTypeConstants.coco/ozar.coffee: flags added, created new objects for the differing properties and assign them on original objects.

* merge ThangTypeConstants.coco/ozar.coffee: flags added, created new objects for the differing properties and assign them on original objects.

* Auto merging .coco/.ozar - right side

* Auto merging .coco/.ozar - left side

* fix missing comma

* missing utils require added

* Auto merging .coco/.ozar - right side

* Auto merging .coco/.ozar - left side

* fix missing comma

* fix failing test:
TypeError: arg is undefined in public/javascripts/test.js line 8459 > eval (line 49)

	ChooseAccountTypeView.prototype.initialize@webpack://codecombat/./app/views/core/CreateAccountModal/ChooseAccountTypeView.coffee?:49:5
	Backbone.View@webpack://codecombat/./node_modules/backbone/backbone.js?:995:21
	CocoView@webpack://codecombat/./app/views/core/CocoView.coffee?:106:36
	ChooseAccountTypeView@webpack://codecombat/./app/views/core/CreateAccountModal/ChooseAccountTypeView.coffee?:18:56
	CreateAccountModal.prototype.initialize@webpack://codecombat/./app/views/core/CreateAccountModal/CreateAccountModal.coco.coffee?:180:38

* fix reversed condition