webpack speed improvement attempt (#752)
* update package-lock with speed analyzer

* remove import glob loader and add speed analyzer plugin.Use MEASURE=true to analyze

* replace deprecated node-sass with sass
https://sass-lang.com/blog/libsass-is-deprecated

* update sass-loader package

* ignoreOrder for now

* fix build error: vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options

* vue and vue-template compiler should be on same version

* fix sass warnings
- replace / by math.div
- remove unused styles
- fix tabs in certain style elements

* change base vue-path which was requiring all template files in app.js
fix compile-static-templates error of push is not a function, in webpack 4 its already a set: https://github.com/webpack-contrib/copy-webpack-plugin/pull/182
copy base files to a new folder so only those are required by vueComponentView

* refactor to levelUtils so that requiring utils in app.js doesn't load level.coffee and related modules

* separate node_modules into a separate bundle
pass nodeModulesHash using compile-static-templates

* add mode in karma config

* extend code instead of copying

* Revert "separate node_modules into a separate bundle"

This reverts commit 91f10c631c72538eeaef70ec439eb948ee987a19.

* change base-empty to extend in vue-base